#!/bin/bash

# Bash prompt constants
SPACE=' '
NEWLINE='\n'
WORKING_DIRECTORY='\w'
WORKING_DIRECTORY_BASENAME='\W'
USERNAME='\u'
HOSTNAME='\h'
HISTORY_NUMBER='\!'
PROMPT_CHARACTER='\$'
TIME_AMPM='\@'

# Window and color constants
WINDOW_TITLE_BEGIN="\[\e]0;"
WINDOW_TITLE_END="\a\]"

COLOR_BLACK="\[\e[0;30m\]"
COLOR_DARK_GRAY="\[\e[1;30m\]"
COLOR_RED="\[\e[0;31m\]"
COLOR_LIGHT_RED="\[\e[1;31m\]"
COLOR_GREEN="\[\e[0;32m\]"
COLOR_LIGHT_GREEN="\[\e[1;32m\]"
COLOR_YELLOW="\[\e[0;33m\]"
COLOR_LIGHT_YELLOW="\[\e[1;33m\]"
COLOR_BLUE="\[\e[0;34m\]"
COLOR_LIGHT_BLUE="\[\e[1;34m\]"
COLOR_MAGENTA="\[\e[0;35m\]"
COLOR_LIGHT_MAGENTA="\[\e[1;35m\]"
COLOR_CYAN="\[\e[0;36m\]"
COLOR_LIGHT_CYAN="\[\e[1;36m\]"
COLOR_LIGHT_GRAY="\[\e[0;37m\]"
COLOR_WHITE="\[\e[1;37m\]"

COLOR_RESET="\[\e[0;0m\]"

# Prompt command function.
PROMPT_COMMAND=__prompt_command
__prompt_command() {
# (We don't indent the contents because we're using continuation strings.)

# Get return code from last command.
local RC_OF_LAST_COMMAND="$?"

# Start with empty prompt
PS1=""

# Window title: "~ user@host"
PS1+="${WINDOW_TITLE_BEGIN}\
${WORKING_DIRECTORY_BASENAME}\
${SPACE}\
${USERNAME}@${HOSTNAME}\
${WINDOW_TITLE_END}"

# Newline
PS1+="${NEWLINE}"

# User@host
PS1+="${COLOR_LIGHT_GREEN}${USERNAME}@${HOSTNAME}${COLOR_RESET}"

# Return code of last command, if non-zero
if [ $RC_OF_LAST_COMMAND != 0 ]; then
    PS1+="${SPACE}${COLOR_RED}(rc:${RC_OF_LAST_COMMAND})${COLOR_RESET}"
fi

# Shell level, if greater than 1
if [ $SHLVL -gt 1 ]; then
    PS1+="${SPACE}${COLOR_YELLOW}(sh:${SHLVL})${COLOR_RESET}"
fi

# Git branch if available
if hash __git_ps1 2>/dev/null ; then
    # export GIT_PS1_SHOWDIRTYSTATE=Y
    # export GIT_PS1_SHOWSTASHSTATE=Y
    # export GIT_PS1_SHOWUNTRACKEDFILES=Y
    # export GIT_PS1_SHOWUPSTREAM=Y
    PS1+="${COLOR_CYAN}$(__git_ps1)${COLOR_RESET}"
fi

# Time of prompt
PS1+="${SPACE}${COLOR_DARK_GRAY}${TIME_AMPM}${COLOR_RESET}"

# Newline
PS1+="${NEWLINE}"

# Working directory
PS1+="${COLOR_GREEN}${WORKING_DIRECTORY}${COLOR_RESET}"

# Newline
PS1+="${NEWLINE}"

# Prompt
PS1+="${PROMPT_CHARACTER}${SPACE}"

}

# vim: filetype=sh
